# Generated by Django 5.0.7 on 2024-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preOrderApp', '0002_rename_menuitems_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='item', to='preOrderApp.category'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='preOrderApp.menuitem'),
        ),
    ]
