# Generated by Django 5.0.6 on 2024-08-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choiceProducts', '0001_initial'),
        ('main', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.branch'),
        ),
    ]
