# Generated by Django 5.1 on 2024-08-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_branch_inventoryitem_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='User',
            new_name='user',
        ),
    ]
