# Generated by Django 5.0.8 on 2024-08-15 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_role'),
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
