# Generated by Django 5.0.8 on 2024-08-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
