# Generated by Django 5.1 on 2024-08-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_service_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='product_service_videos/')),
                ('link', models.URLField()),
            ],
        ),
    ]
