# Generated by Django 5.1 on 2024-08-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='image',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='video',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
