# Generated by Django 5.0.8 on 2024-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productService', '0002_alter_productservice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='image',
            field=models.ImageField(upload_to='productService/images/'),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='productService/videos/'),
        ),
    ]
