# Generated by Django 5.0.6 on 2024-08-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_profile'),
        ('productService', '0003_alter_productservice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
